# Site settings
site: Moe
title: Moe - Personal blog
keywords: personal, blog, developer, it consultant
description: >-
    Moe - Blog
lang: en-US
timezone:  Europe/Paris

# Author settings
author:
  name: The Coolest Moe
  bio: Full-Stack developer <br> IT Consultant @PowerM <br> Open Source /#linux
  picture: assets/images/profile.webp
  github: majnioui
  twitter: _marocain
  instagram: m.majnioui
  linkedin: elmajnioui
  email: mo@majnioui.me


# URL settings
url: "https://coolest.moe"
permalink: pretty

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge


exclude:
  - .jekyll-cache
  - .obsidian
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - CONTRIBUTING.md

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-relative-links
paginate: 20
paginate_path: "/page/:num"

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:slug

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

relative_links:
  enabled:     true
  collections: false